### ISSUE TITLE
Rename getData endpoint

### ISSUE THREAD

**Issue by nuest** [52North/series-rest-api#109]
The API is only REST**ful**, so we should not impose any hard standards on naming things. But the ``/getData`` should be renamed to ``/data``, since ``GET`` is already the HTTP verb:

``/api/v1/timeseries/{id}/data``

**Comment by ridoo** [comment]
will be fixed within version 2.x. there you'll have additional endpoints which add support for more sensor types: besides `stationary` and `insitu` (the `station` endpoint) namely `remote` and `mobile`.

also we will be able to add more and more observation types (before only `timeseries` = `measurement`). From v2 we support also `count`, `boolean`, `text`, ... and some more. Further types may be added in the future.

the `data` endpoint will be available on `/datasets/{id}/data` or `/datasets/data`. However, `/timeseries/getData` and `/timeseries/{id}/getData` won't be changed for backward compatibility, though.
