### ISSUE TITLE
Implement Paging for DAO SPI implemenation

### ISSUE THREAD

**Issue by ridoo** [52North/series-rest-api#129]
Database paging via Hibernate API. Actual mechanism ([multiple mechanism possible](http://www.baeldung.com/hibernate-pagination)) has to be determined.

Use a `Paginated` object to hold page info and add it to the actual output.

Revise Paging section in documentation. Have a look at serving [partial content via `Content-Range`](https://tools.ietf.org/html/rfc7233#section-4.2) and decide to use it (or not).

**Comment by nuest** [comment]
@autermann often pointed out the lack of paging and might be able to provide some insight or ideas.

**Comment by CarstenHollmann** [comment]
To ensure no objects are returned twice the `ORDER BY` statemente must be added to the db queries because the dbms does not guarantee the same result order if the request is executed again.

**Comment by ridoo** [comment]
@SpeckiJ is there any update on this? :)
