### ISSUE TITLE
Add support for time periods / duration

### ISSUE THREAD

**Issue by nuest** [52North/series-rest-api#157]
At download time (CSV export) a user wants both values (begin and end time of an observation), which are stored in the SOS database (`observation` table, fields `phenomeonTimeStart` and `phenomenonTimeEnd`) and available via the SOS API (TimePeriod, if the DB values are the same then the API returns TimeInstant).

**BUT** right now the REST API only exposes **one** date, which can be based on different values depending on the used database schema or data source. In case of direct database access the field is `phenomenontimeend`.

**Goal**: expose both values, either as two different fields, or by putting an ISO8601 string into the time field. This also has implications on the query API, but for starters a default "if the observation inverval touches/overlaps the query interval it is a match" should be sufficient.

**Comment by nuest** [comment]
@CarstenHollmann @ridoo Please review.

**Comment by ridoo** [comment]
As discussed (some time) before, I would prefer outputting an ISO8601 period. To stay backward compatible a further query parameter could determine that both values `phenomeonTimeStart` and `phenomeonTimeEnd` are of interest.

I agree querying has to be extended. I do not see any problem in realizing it the way you suggested.

**Comment by ridoo** [comment]
Opposed to my previous favorite using ISO8601 period, we chose to use `timestart` in addition to `timestamp` to stay backwards compatible. Intervals can be retrieved by adding the query parameter `showtimeintervals=true` (see detailed description at  https://github.com/52North/series-rest-api/pull/266).
