### ISSUE TITLE
Add CRS to GeoJSON Features in /stations

### ISSUE THREAD

**Issue by matuchevsky** [52North/series-rest-api#160]

**Comment by ridoo** [comment]
@matuchevsky to quote [documentation](http://52north.github.io/sensorweb-rest-api/#stations-query-parameters) here:
> The client indicates that input geometries shall be interpreted as being referenced by the given CRS (in this case to 'EPSG:25832' (ETRS89 / UTM zone 32N)).
>
> Per default geometries are referenced by the WGS84 CRS (precisely: CRS84, lon/lat order). If crs value differs from default, all output geometries are transformed to match the asked CRS.
>
> Please note that some CRS switch coordinate axes. Double check axes ordering before interpreting coordinates!

Per default all coordinates are expected to be GeoJSON CRS default. For a CRS different to WGS84 in lon/lat axes order the CRS should be returned [as defined by GeoJSON spec](http://geojson.org/geojson-spec.html#coordinate-reference-system-objects).
