### ISSUE TITLE
Ignore invalid reference timeseries

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/series-rest-api#174]
When a timeseries has an invalid reference timeseries, the orignial timeseries is not returned when the expanded request parameter is set to true. 

e.g.
/api/v1/timeseries/123?expanded=true

In our case the lastValue attribute of the reference series was NULL. 

The API throws an unexpected Error due to an internal NullPointer Exception. See attachment.

[Exception access series with reference series.txt](https://github.com/52North/series-rest-api/files/274187/Exception.access.series.with.reference.series.txt)

**Comment by ridoo** [comment]
should be fixed by #205 and #200, repectively #206
