### ISSUE TITLE
API Service Title

### ISSUE THREAD

**Issue by dbciar** [52North/series-rest-api#365]
Hi All,

I'm not 100% sure if this is the right repo to raise this, so let me know if it should be somewhere else.

So, I'm running the 52North SOS bundle, `52n-sensorweb-sos-bundle-4.3.8`, downloaded from the 52north.org site.  There is data in the SOS node and we are accessing it using the Helgoland client.  When looking at the 'Provider' details of the SOS node as displayed in the client, it has the default label 'My Timeseries Service.'  I haven't been able to locate where I can change the service's label on the SOS node to something other than the default.

![52nrest-api-service-details](https://cloud.githubusercontent.com/assets/8082568/25657244/d54807e6-2ff4-11e7-9454-771b5509805e.png)

Can anyone help in letting me know how to customize this?

Thanks,
David

**Comment by ridoo** [comment]
@dbciar yes and no :). The SOS version you are using bundles/ships the Series API but contains an own configuration entry.

You can configure the service information under `WEB-INF/spring/timeseries-api_v1_beans.xml`. When building the SOS from source, you can change those settings directly [within the webapp-bundle](https://github.com/52North/SOS/blob/4.3.8/webapp-bundle/src/main/webapp/WEB-INF/spring/timeseries-api_v1_beans.xml#L11-L14) module of the SOS.

**Comment by dbciar** [comment]
Thanks - I'll give it a go.
