### ISSUE TITLE
Install document?

### ISSUE THREAD

**Issue by gamesbook** [52North/series-rest-api#439]
Is there a link to an installation document?

**Comment by ridoo** [comment]
no, currently there is no install document. however, the `series-rest-api` defines a Web interface and an SPI (service provider interface) and does not stand alone (at least versions from `2.x`). 

If you have series data within a database you should use the https://github.com/52North/dao-series-api. What's your use case?

**Comment by gamesbook** [comment]
Thanks for the pointer to the DAO; I will look at that for guidance,
