### ISSUE TITLE
Set decimal precision in timeseries queries

### ISSUE THREAD

**Issue by heliosqs** [52North/series-rest-api#478]
**Information**
_sos version:_ 4.4.7
_database:_ postgres

**Issue description**
When I request the timeseries endpoint:
http://host/api/timeseries/24/data?timespan=2019-08-01T13:00:00Z/2019-08-28T13:00:00Z
I get the response in which each value has a precision of a maximum of three decimal positions. As seen in the following image.
![Screenshot from 2019-12-02 15-01-15](https://user-images.githubusercontent.com/27177400/69990929-ab8e9980-1514-11ea-90e5-159830431f9b.png)

But I have confirmed that the table numericvalue in the database has all the corresponding decimals.
![Screenshot from 2019-12-02 15-03-09](https://user-images.githubusercontent.com/27177400/69991070-fdcfba80-1514-11ea-8fa1-ebab87279b84.png)

**Expected behavior**
Is there a way to set the decimal precision on the API or the configuration files?

Thanks

**Comment by CarstenHollmann** [comment]
The decimal precision is defined in the `DatasetResource.hbm.xml` Hibernate mapping file. You find this file in the folder `\WEB-INF\classes\mapping\extension\readonly\default` of the depoyed SOS/REST-API.

In line 35 you find this definition `<property formula="3" name="numberOfDecimals" type="int" />`

Change `3` to the decimal precision that should be displayed, save the changes and reload the SOS/REST-API.
